### ISSUE TITLE
Pre-training model cannot be downloaded

### ISSUE THREAD

**Issue by taoshiqian** [umich-vl/pose-ae-demo#9]
Pre-training model cannot be downloaded.
Thank you for your work, I can't download the pre-training model from the link you gave, can you give other download links, such as Google Driver, Baidu Wangpan, etc. Thank you very much.

**Comment by taoshiqian** [comment]
I got it from your link. Thanks

**Comment by WinstonDeng** [comment]
@taoshiqian Hi, can you share a pre-trained model? The link fails to download now.
